language: node_js
node_js:
  - 10

stages:
  - linting
  - typechecking
  - testing

jobs:
  - stage: linting
    script: npm run lint
  - stage: typechecking
    script: npm run typecheck
  - stage: testing
    script: CI=true npm run test
