name: Build and Publish to NPM

on:
  pull_request:
    branches:
      - master
    types: [closed]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build and Publish
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SETTER_CI_TOKEN }}
      - name: Set up Git
        run: |
          git config --global user.email "dev@setter.com"
          git config --global user.name "setterbot"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Patch Version
        if: "!contains(github.event.head_commit.message, 'BREAKING CHANGE') && !contains(github.event.head_commit.message, 'feature')"
        run: |
          echo ::set-env name=VERSION::$(npm version patch -f)
      - name: Minor Version
        if: "contains(github.event.head_commit.message, 'feature')"
        run: |
          echo ::set-env name=VERSION::$(npm version minor -f)
      - name: Major Version
        if: "contains(github.event.head_commit.message, 'BREAKING CHANGE')"
        run: |
          echo ::set-env name=VERSION::$(npm version major -f)
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Housekeeping
        run: |
          git push -f
          git push --tags
